package com.elevare.active

data class Evidence(val id:String,val title:String,val category:String,val pmid:String,val population:String,val finding:String,val limit:String,val takeaway:String)
object Research{
 val articles=listOf(
 Evidence("sprint","Sprint, GH ve boy: aynı şey mi?","Egzersiz","12137178","9 erkek · 6 ve 30 saniyelik maksimal bisiklet sprinti · 2002","Çalışma sprint sonrası kısa süreli kandaki hGH yanıtını inceledi. 30 saniyelik sprint sonrası ölçülen en yüksek ortalama, 6 saniyelik sprint sonrasından yüksekti.","Boy uzaması ölçülmedi. Bireyler arasında büyük farklılık vardı. Bu sonuçtan ergenler için boy artırıcı bir sprint reçetesi çıkarılamaz. Araştırma özeti ile verilen ortalamaların yüzdelik ifadesi de tutarlı değildir; uygulama bunu büyüme yüzdesine dönüştürmez.","Sprint araştırması var; boy kazanımı garantisi yok. Uygulamadaki seans koşuya hazırlıktır, deneyin maksimal sprint protokolü değildir."),
 Evidence("milk","Süt içmek daha uzun olmak demek mi?","Beslenme","30839054","6–18 yaş · 17 randomize çalışma · 2.844 katılımcı · 2019","Bu meta-analiz, süt ve süt ürünü müdahalelerinde kontrol grubuna göre boy değişiminde anlamlı fark bulmadı.","Beslenme durumu, çalışma süresi ve sonuçlar değişebilir. Bir besin grubunun büyümeyle ilişkisi, herkesin daha fazla tüketerek daha uzun olacağını göstermez.","Süt ürünleri besin öğeleri sağlar; santimetre garantisi değildir. Alerji, intolerans veya tercih nedeniyle süt tüketmiyorsan bu bir başarısızlık değil."),
 Evidence("breath","Nefes çalışmalarından ne beklemeli?","Nefes","36630953","Bir ay · günlük 5 dakika · randomize kontrollü çalışma · 2023","Nefes çalışmaları duygu durumu ve fizyolojik uyarılma açısından değerlendirildi. Özellikle veriş odaklı yaklaşım umut verici bulundu.","Boy veya GH artışı çalışmanın hedef sonucu değildi. Uygulamadaki rahat 4/6 ritmi araştırmanın tüm müdahalelerini birebir tekrar etmez.","Nefes alanının amacı rahat bir mola vermek. Rahatsızlıkta doğal nefesine dön; nefes tutma ve hiperventilasyon görevi yok."),
 Evidence("breath-gh","Nefes ve hormon: deney neydi?","Kanıt sınırı","3100467","11 antrenmanlı kişi · ortalama 24,5 yaş · 1986","Hiperventilasyon ve nefes tutma deneylerinden sonra kısa süreli hormonal değişimler bildirildi.","Boy uzaması ve gençlerde evde kullanımın güvenliği gösterilmedi. Bu deneyler rahat nefes molasıyla aynı şey değildir.","Bu çalışmayı boy artırıcı görev olarak uygulamıyoruz. Bir hormonun kısa süreli değişmesi daha fazla büyüme anlamına gelmez."),
 Evidence("uv","UVB çalışması neyi kanıtlamıyor?","Kanıt sınırı","34433056","Fare deneyleri ve bazı insan ölçümleri · deri-beyin-gonad ekseni · 2021","Araştırma deriye UVB maruziyeti ile bazı seks hormonu ve davranış ölçümlerini ele aldı.","Genital bölgeyi güneşlendirmenin ergenlerde boy uzattığını göstermedi. Testosteron, GH ve boy farklı sonuçlardır. UV maruziyeti cilde zarar verebilir.","Testis güneşlendirme bu uygulamanın bir görevi veya önerisi değildir. Güneşten korunma önemlidir."),
 Evidence("bone","Kemik sağlığı ile boy farkı","Beslenme","31089738","Çocuk ve ergenlerde 13 makale · sistematik derleme · 2019","Süt ürünleri eklenmesiyle kemik mineral içeriğinde artış bildirildi; doğrusal büyüme sonuçları belirsizdi.","Kemik mineral içeriği, kemiğin uzaması veya final boy ile aynı ölçüm değildir.","Bilim kartlarında her zaman neyin ölçüldüğüne bak. Bir PMID, her pazarlama cümlesini doğrulamaz.")
 )
 fun article(id:String)=articles.first{it.id==id}
}
